---
title: "Your blog post title"
date: YYYY-MM-DD
---

title: Your awesome title
theme: minima
author: Elon
email: lejw4667@yonsei.ac.kr
description: > # this means to ignore newlines until "baseurl:"

  my Great Projects and my company's products will be based on my GitHub pages.
  
  Thank you!
  
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  elominatedCloud

show_excerpts: true # set to false to remove excerpts on the homepage
